### ISSUE TITLE
Poor diagnostics from missing `set_stopped_t`.

### ISSUE THREAD

**Issue by williamspatrick** [NVIDIA/stdexec#872]
After a rebase, when compiling with GCC 12, I'm encountering a compile error attempting to use a deleted tuple function.

```
stdexec/execution.hpp:4656:88: error: use of deleted function ‘std::enable_if_t<(! __exactly_once<_Tp>)> std::variant<_Types>::emplace(_Args&& ...) [with _Tp = std::tuple<stdexec::__receivers::set_stopped_t>; _Args = {stdexec::__receivers::set_stopped_t}; _Types = {std::monostate, std::tuple<stdexec::__receivers::set_value_t, sdbusplus::message::message>}; std::enable_if_t<(! __exactly_once<_Tp>)> = void]’
```

The full log is as follows:
```
../include/sdbusplus/async/stdexec/execution.hpp: In instantiation of ‘static void stdexec::__schedule_from::__receiver1<_SchedulerId, _CvrefSenderId, _ReceiverId>::__t::__complete_(_Tag, stdexec::__schedule_from::__receiver1<_SchedulerId, _CvrefSenderId, _ReceiverId>::__t&&, _Args&& ...) [with _Tag = stdexec::__receivers::set_stopped_t; _Args = {}; _SchedulerId = stdexec::_Yp<exec::any_receiver_ref<stdexec::completion_signatures<stdexec::__receivers::set_error_t(std::__exception_ptr::exception_ptr), stdexec::__receivers::set_stopped_t()> >::any_sender<>::any_scheduler<> >; _CvrefSenderId = stdexec::_Yp<sdbusplus::async::match_ns::match_sender>; _ReceiverId = stdexec::__as_awaitable::__receiver<stdexec::_Yp<exec::__task::basic_task<void, exec::__task::__default_task_context_impl<exec::__task::__scheduler_affinity::__sticky> >::__promise>, sdbusplus::message::message>]’:
../include/sdbusplus/async/stdexec/execution.hpp:4668:13:   required from ‘void stdexec::__schedule_from::tag_invoke(_Tag, __receiver1<_SchedulerId, _CvrefSenderId, _ReceiverId>::__t&&, _Args&& ...) [with _Tag = stdexec::__receivers::set_stopped_t; _Args = {}; _SchedulerId = stdexec::_Yp<exec::any_receiver_ref<stdexec::completion_signatures<stdexec::__receivers::set_error_t(std::__exception_ptr::exception_ptr), stdexec::__receivers::set_stopped_t()> >::any_sender<>::any_scheduler<> >; _CvrefSenderId = stdexec::_Yp<sdbusplus::async::match_ns::match_sender>; _ReceiverId = stdexec::__as_awaitable::__receiver<stdexec::_Yp<exec::__task::basic_task<void, exec::__task::__default_task_context_impl<exec::__task::__scheduler_affinity::__sticky> >::__promise>, sdbusplus::message::message>]’
../include/sdbusplus/async/stdexec/functional.hpp:108:26:   required from ‘constexpr stdexec::__tag_invoke::tag_invoke_result_t<_Tag, _Args ...> stdexec::__tag_invoke::tag_invoke_t::operator()(_Tag, _Args&& ...) const [with _Tag = stdexec::__receivers::set_stopped_t; _Args = {stdexec::__schedule_from::__receiver1<stdexec::_Yp<exec::any_receiver_ref<stdexec::completion_signatures<stdexec::__receivers::set_error_t(std::__exception_ptr::exception_ptr), stdexec::__receivers::set_stopped_t()> >::any_sender<>::any_scheduler<> >, stdexec::_Yp<sdbusplus::async::match_ns::match_sender>, stdexec::__as_awaitable::__receiver<stdexec::_Yp<exec::__task::basic_task<void, exec::__task::__default_task_context_impl<exec::__task::__scheduler_affinity::__sticky> >::__promise>, sdbusplus::message::message> >::__t}; stdexec::__tag_invoke::tag_invoke_result_t<_Tag, _Args ...> = void]’
../include/sdbusplus/async/stdexec/execution.hpp:372:26:   required from ‘void stdexec::__receivers::set_stopped_t::operator()(_Receiver&&) const [with _Receiver = stdexec::__schedule_from::__receiver1<stdexec::_Yp<exec::any_receiver_ref<stdexec::completion_signatures<stdexec::__receivers::set_error_t(std::__exception_ptr::exception_ptr), stdexec::__receivers::set_stopped_t()> >::any_sender<>::any_scheduler<> >, stdexec::_Yp<sdbusplus::async::match_ns::match_sender>, stdexec::__as_awaitable::__receiver<stdexec::_Yp<exec::__task::basic_task<void, exec::__task::__default_task_context_impl<exec::__task::__scheduler_affinity::__sticky> >::__promise>, sdbusplus::message::message> >::__t]’
../include/sdbusplus/async/match.hpp:116:31:   required from ‘void sdbusplus::async::match_ns::match_operation<Receiver>::stop() [with Receiver = stdexec::__schedule_from::__receiver1<stdexec::_Yp<exec::any_receiver_ref<stdexec::completion_signatures<stdexec::__receivers::set_error_t(std::__exception_ptr::exception_ptr), stdexec::__receivers::set_stopped_t()> >::any_sender<>::any_scheduler<> >, stdexec::_Yp<sdbusplus::async::match_ns::match_sender>, stdexec::__as_awaitable::__receiver<stdexec::_Yp<exec::__task::basic_task<void, exec::__task::__default_task_context_impl<exec::__task::__scheduler_affinity::__sticky> >::__promise>, sdbusplus::message::message> >::__t]’
../include/sdbusplus/async/match.hpp:114:10:   required from here
../include/sdbusplus/async/stdexec/execution.hpp:4656:88: error: use of deleted function ‘std::enable_if_t<(! __exactly_once<_Tp>)> std::variant<_Types>::emplace(_Args&& ...) [with _Tp = std::tuple<stdexec::__receivers::set_stopped_t>; _Args = {stdexec::__receivers::set_stopped_t}; _Types = {std::monostate, std::tuple<stdexec::__receivers::set_value_t, sdbusplus::message::message>}; std::enable_if_t<(! __exactly_once<_Tp>)> = void]’
 4656 |           __self.__op_state_->__data_.template emplace<__decayed_tuple<_Tag, _Args...>>(
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
 4657 |             _Tag{}, (_Args&&) __args...);
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                
/usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/variant:1589:43: note: declared here
 1589 |         enable_if_t<!__exactly_once<_Tp>> emplace(_Args&&...) = delete;
 ```

**Comment by williamspatrick** [comment]
I was last successfully compiling with 268b9d858c0a0e63af4806c3065dc096319375d6 , if that is helpful at all.

What isn't obvious is that, other than a clang-format commit, the most recent touch of this line was 46f1b2d5 in November:

```
46f1b2d5 include/stdexec/execution.hpp (Georgy Evtushenko                2022-11-03 14:24:08 +0400 4506)             __self.__op_state_->__data_.template emplace<__decayed_tuple<_Tag, _Args...>>(_Tag{}, (_Args&&) __args...);
```

**Comment by maikel** [comment]
The errors says that the match operation wants to store a `set_stopped_t` signal but the (materialized) variant only knows of `set_value_t`. I think what might have changed are some computations for `completion_signatures`. For example, I've changed the computation of completion sigs in `when_all`. I'll look into sdbusplus and try to track that down.

**Comment by maikel** [comment]
The match sender has the following lines

```cpp
struct match_sender
{
    match_sender() = delete;
    explicit match_sender(match& m) noexcept : m(m){};


    friend auto tag_invoke(execution::get_completion_signatures_t,
                           const match_sender&, auto)
        -> execution::completion_signatures<execution::set_value_t(message_t)>;


    template <execution::receiver R>
    friend auto tag_invoke(execution::connect_t, match_sender&& self, R r)
        -> match_operation<R>
    {
        return {self.m, std::move(r)};
    }


  private:
    match& m;
};
```

Here, the completion_signatures are only `set_value_t` but you actually emit `set_stopped_t`. Thats wrong. Might this be an issue?

**Comment by williamspatrick** [comment]
> I'll look into sdbusplus and try to track that down.

@maikel - Wow, thanks much!  You didn't have to go through that much effort, but I appreciate it.

I should have started this with "This is quite likely something wrong with my code but I'm having trouble deciphering the compiler errors."

I'll leave an [obligatory link](https://twitter.com/ericniebler/status/1643038876880240641?s=20) for @ericniebler and change the title of this issue. ;)
