### ISSUE TITLE
[sequence_senders] item_types_of_t probes sequence item senders with the regular __debug_sender when STDEXEC_ENABLE_EXTRA_TYPE_CHECKING=ON

### ISSUE THREAD

**Issue by alwaysprince05** [NVIDIA/stdexec#2273]
Requested by @ericniebler in #2271 — follow-up found while verifying that PR with `-DSTDEXEC_ENABLE_EXTRA_TYPE_CHECKING=ON`. Fails on pristine `main`, so it is separate from the fix in #2271.

### Description

With extra type checking enabled, `item_types_of_t` (and its `__item_types_of` helpers) still route sequence item senders through the *regular* debug sender machinery (`__debug_sender`), which calls `connect()` on them. Sequence senders are not regular senders, so compilation fails with:

```
no matching function for call to object of type 'stdexec::connect_t'
```

#2271 fixed the analogous paths (`__sequence_receiver_from`, `subscribe_t::__type_check_arguments`) by switching to `__sequence_completion_signatures_of_t`; the item-type probing paths need the same sequence-aware treatment (or a sequence-aware equivalent of `__debug_sender`).

### Reproduction

Compose an `exec::any_sequence_sender` pipeline and build with the flag enabled. After #2271, the remaining sequence-test errors under the flag largely come from this path (error counts across the sequence test files drop from 20/58/66 on `main` to 4/6/16 with #2271).
