### ISSUE TITLE
Build failed in debug mode with gcc11

### ISSUE THREAD

**Issue by npuichigo** [NVIDIA/stdexec#915]
I ran into an linkage issue when building in debug mode with gcc11. Here's the error log.

```
CC=gcc-11 CXX=g++-11 cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build
cmake --build build -- -j 20

......
[100%] Linking CXX executable test.stdexec
/usr/bin/ld: CMakeFiles/test.stdexec.dir/exec/test_any_sender.cpp.o: warning: relocation against `_ZN7stdexec24get_completion_schedulerINS_11__receivers11set_value_tEEE' in read-only section `.text'
/usr/bin/ld: CMakeFiles/test.stdexec.dir/stdexec/cpos/test_cpo_upon_error.cpp.o: in function `____C_A_T_C_H____T_E_S_T____0()':
/home/ichigo/stdexec/test/stdexec/cpos/test_cpo_upon_error.cpp:47: undefined reference to `stdexec::get_completion_scheduler<stdexec::__receivers::set_error_t>'
/usr/bin/ld: CMakeFiles/test.stdexec.dir/stdexec/cpos/test_cpo_upon_stopped.cpp.o: in function `____C_A_T_C_H____T_E_S_T____0()':
/home/ichigo/stdexec/test/stdexec/cpos/test_cpo_upon_stopped.cpp:47: undefined reference to `stdexec::get_completion_scheduler<stdexec::__receivers::set_stopped_t>'
/usr/bin/ld: CMakeFiles/test.stdexec.dir/stdexec/algos/factories/test_transfer_just.cpp.o: in function `____C_A_T_C_H____T_E_S_T____30()':
/home/ichigo/stdexec/test/stdexec/algos/factories/test_transfer_just.cpp:161: undefined reference to `stdexec::get_completion_scheduler<stdexec::__receivers::set_value_t>'
/usr/bin/ld: /home/ichigo/stdexec/test/stdexec/algos/factories/test_transfer_just.cpp:164: undefined reference to `stdexec::get_completion_scheduler<stdexec::__receivers::set_stopped_t>'
/usr/bin/ld: /home/ichigo/stdexec/test/stdexec/algos/factories/test_transfer_just.cpp:168: undefined reference to `stdexec::get_completion_scheduler<stdexec::__receivers::set_value_t>'
/usr/bin/ld: /home/ichigo/stdexec/test/stdexec/algos/factories/test_transfer_just.cpp:171: undefined reference to `stdexec::get_completion_scheduler<stdexec::__receivers::set_stopped_t>'
/usr/bin/ld: /home/ichigo/stdexec/test/stdexec/algos/factories/test_transfer_just.cpp:175: undefined reference to `stdexec::get_completion_scheduler<stdexec::__receivers::set_value_t>'
/usr/bin/ld: /home/ichigo/stdexec/test/stdexec/algos/factories/test_transfer_just.cpp:178: undefined reference to `stdexec::get_completion_scheduler<stdexec::__receivers::set_stopped_t>'
/usr/bin/ld: CMakeFiles/test.stdexec.dir/stdexec/algos/adaptors/test_transfer.cpp.o: in function `decltype (tag_invoke((__declval<stdexec::__transfer::transfer_t>)(), (__declval<decltype (((__declval<stdexec::__queries::get_completion_scheduler_t<stdexec::__receivers::set_value_t> >)())((__declval<decltype (((__declval<stdexec::__env::get_env_t>)())((__declval<stdexec::__schedule_from::__sender<impulse_scheduler, stdexec::__just::__sender<val_type3> >::__t const&>)()))>)()))>)(), (__declval<stdexec::__schedule_from::__sender<impulse_scheduler, stdexec::__just::__sender<val_type3> >::__t>)(), (__declval<inline_scheduler>)())) stdexec::__transfer::transfer_t::operator()<stdexec::__schedule_from::__sender<impulse_scheduler, stdexec::__just::__sender<val_type3> >::__t, inline_scheduler>(stdexec::__schedule_from::__sender<impulse_scheduler, stdexec::__just::__sender<val_type3> >::__t&&, inline_scheduler&&) const':
/home/ichigo/stdexec/include/stdexec/execution.hpp:4916: undefined reference to `stdexec::get_completion_scheduler<stdexec::__receivers::set_value_t>'
/usr/bin/ld: CMakeFiles/test.stdexec.dir/stdexec/algos/adaptors/test_then.cpp.o: in function `____C_A_T_C_H____T_E_S_T____26()':
/home/ichigo/stdexec/test/stdexec/algos/adaptors/test_then.cpp:127: undefined reference to `stdexec::get_completion_scheduler<stdexec::__receivers::set_value_t>'
/usr/bin/ld: /home/ichigo/stdexec/test/stdexec/algos/adaptors/test_then.cpp:131: undefined reference to `stdexec::get_completion_scheduler<stdexec::__receivers::set_stopped_t>'
/usr/bin/ld: CMakeFiles/test.stdexec.dir/stdexec/algos/adaptors/test_then.cpp.o: in function `auto stdexec::__then::then_t::operator()<stdexec::__schedule_from::__sender<inline_scheduler, stdexec::__just::__sender<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::__t, ____C_A_T_C_H____T_E_S_T____40()::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)#1}>(stdexec::__schedule_from::__sender<inline_scheduler, stdexec::__just::__sender<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::__t&&, ____C_A_T_C_H____T_E_S_T____40()::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)#1}) const':
/home/ichigo/stdexec/include/stdexec/execution.hpp:2875: undefined reference to `stdexec::get_completion_scheduler<stdexec::__receivers::set_value_t>'
/usr/bin/ld: CMakeFiles/test.stdexec.dir/stdexec/algos/adaptors/test_let_value.cpp.o: in function `auto stdexec::__let::__let_xxx_t<stdexec::__let::let_value_t, stdexec::__receivers::set_value_t>::operator()<stdexec::__schedule_from::__sender<inline_scheduler, stdexec::__just::__sender<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::__t, ____C_A_T_C_H____T_E_S_T____40()::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)#1}>(stdexec::__schedule_from::__sender<inline_scheduler, stdexec::__just::__sender<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::__t&&, ____C_A_T_C_H____T_E_S_T____40()::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)#1}) const':
/home/ichigo/stdexec/include/stdexec/execution.hpp:4212: undefined reference to `stdexec::get_completion_scheduler<stdexec::__receivers::set_value_t>'
/usr/bin/ld: CMakeFiles/test.stdexec.dir/stdexec/algos/adaptors/test_let_error.cpp.o: in function `auto stdexec::__let::__let_xxx_t<stdexec::__let::let_error_t, stdexec::__receivers::set_error_t>::operator()<stdexec::__schedule_from::__sender<inline_scheduler, stdexec::__just::__sender<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::__t, ____C_A_T_C_H____T_E_S_T____38()::{lambda(std::__exception_ptr::exception_ptr)#1}>(stdexec::__schedule_from::__sender<inline_scheduler, stdexec::__just::__sender<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::__t&&, ____C_A_T_C_H____T_E_S_T____38()::{lambda(std::__exception_ptr::exception_ptr)#1}) const':
/home/ichigo/stdexec/include/stdexec/execution.hpp:4212: undefined reference to `stdexec::get_completion_scheduler<stdexec::__receivers::set_value_t>'
/usr/bin/ld: CMakeFiles/test.stdexec.dir/stdexec/algos/adaptors/test_let_stopped.cpp.o: in function `auto stdexec::__let::__let_xxx_t<stdexec::__let::let_stopped_t, stdexec::__receivers::set_stopped_t>::operator()<stdexec::__schedule_from::__sender<inline_scheduler, stdexec::__just::__sender<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::__t, ____C_A_T_C_H____T_E_S_T____32()::{lambda()#1}>(stdexec::__schedule_from::__sender<inline_scheduler, stdexec::__just::__sender<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::__t&&, ____C_A_T_C_H____T_E_S_T____32()::{lambda()#1}) const':
/home/ichigo/stdexec/include/stdexec/execution.hpp:4212: undefined reference to `stdexec::get_completion_scheduler<stdexec::__receivers::set_value_t>'
/usr/bin/ld: CMakeFiles/test.stdexec.dir/stdexec/algos/adaptors/test_bulk.cpp.o: in function `auto stdexec::__bulk::bulk_t::operator()<stdexec::__schedule_from::__sender<exec::static_thread_pool::scheduler, stdexec::__just::__sender<> >::__t, int, ____C_A_T_C_H____T_E_S_T____28()::{lambda(int)#1}>(stdexec::__schedule_from::__sender<exec::static_thread_pool::scheduler, stdexec::__just::__sender<> >::__t&&, int, ____C_A_T_C_H____T_E_S_T____28()::{lambda(int)#1}) const':
/home/ichigo/stdexec/include/stdexec/execution.hpp:3304: undefined reference to `stdexec::get_completion_scheduler<stdexec::__receivers::set_value_t>'
/usr/bin/ld: CMakeFiles/test.stdexec.dir/stdexec/algos/adaptors/test_bulk.cpp.o:/home/ichigo/stdexec/include/stdexec/execution.hpp:3304: more undefined references to `stdexec::get_completion_scheduler<stdexec::__receivers::set_value_t>' follow
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
gmake[2]: *** [test/CMakeFiles/test.stdexec.dir/build.make:1121: test/test.stdexec] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:926: test/CMakeFiles/test.stdexec.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2
```

**Comment by maikel** [comment]
Yup same here.

**Comment by msimberg** [comment]
This is reproducible with GCC 10 to 13 and was introduced by https://github.com/NVIDIA/stdexec/pull/907. Specifically, the change to add `template <__completion_tag _CPO> extern const get_completion_scheduler<_CPO> get_completion_scheduler;` to `__execution_fwd.hpp`.

Small reproducer on compiler explorer: https://godbolt.org/z/hMTjjETc6.

GCC's behaviour seems reasonable to me, as does clang's. Is the `extern` declaration essential (for bloat, compilation times, something else?) or could it be disabled for GCC? Note that `get_completion_scheduler` is the only templated CPO, the other CPOs are not affected.

**Comment by ericniebler** [comment]
Why does the gcc-11 build, link, and test in CI? And why do my local gcc-11 & -12 builds work locally? I don't get it.

**Comment by ericniebler** [comment]
> This seems to only be happening without optimizations

Thanks, this was what I was missing. Thx also to @maikel who pointed out the same.
